name: learn yaml for devops

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    workflow_dispatch:

jobs:
  yaml-test:
    runs-on: ubuntu-latest
    steps:
     - name: Print-hello
       run: echo "Hello From the Other Side!"
     - name: Print-goodbye
       run: echo "Good-Bye From the Other Side!"


